### ISSUE TITLE
Add option to ignore missing flags sets if they don't exist instead of raising an exception

### ISSUE THREAD

**Issue by SpheMakh** [ska-sa/owlcat#49] opened 2019-07-12 10:26 UTC

**Comment by o-smirnov** [comment] 2019-07-12 15:07
OK, so this is for ``flag-ms -r`` I assume, you want it to ignore unknown flagsets, and only remove the known ones.

**Comment by o-smirnov** [comment] 2019-07-12 15:10
I think it already does just that!

**Comment by o-smirnov** [comment] 2019-07-12 15:34
Duplicate of #30 

Third time lucky!

**Closed by o-smirnov** 2019-07-12 15:34 UTC
Labels: enhancement
