### ISSUE TITLE
flag-ms will not remove legacy flagset

### ISSUE THREAD

**Issue by JSKenyon** [ska-sa/owlcat#35] opened 2018-01-16 09:05 UTC
Encountered this while trying to remove all flagsets on some 3C147 data. Managed to remove all flagsets with the exception of the legacy flagset. The flagset appears when running `flag-ms -l`, but `flag-ms -r legacy` cannot find it.

**Comment by o-smirnov** [comment] 2019-07-12 15:34
Duplicate of #30

**Closed by o-smirnov** 2019-07-12 15:34 UTC
